[build]
command = "npm run build"
publish = "build"

[build.environment]
CYPRESS_CACHE_FOLDER = "/opt/buildhome/.cache/Cypress"
TERM = "xterm"

[[plugins]]
package = "netlify-plugin-cypress"
  [plugins.inputs]
    enable = false
  [plugins.inputs.postBuild]
    record = true
    enable = true